$TAGS = [
  "REB", #Rebels
  "PIR", #Pirates
  "NAT", #Natives
  "SWE", #Sweden
  "DAN", #Denmark
  "FIN", #Finland
  "GOT", #Gotland
  "NOR", #Norway
  "SHL", #Holstein
  "SCA", #Scandinavia
  "ACH", #Achaea
  "ALB", #Albania
  "ATH", #Athens
  "BOS", #Bosnia
  "BUL", #Bulgaria
  "BYZ", #Byzantine
  "CEP", #Corfu
  "CRO", #Croatia
  "CRT", #Crete
  "CYP", #Cyprus
  "EPI", #Epirus
  "GRE", #Greece
  "HUN", #Hungary
  "KNI", #Knights
  "MOE", #Morea
  "MOL", #Moldavia
  "MON", #Montenegro
  "NAX", #Naxos
  "RAG", #Ragusa
  "RMN", #Romania
  "SER", #Serbia
  "TRA", #Transylvania
  "TUR", #Ottomans
  "WAL", #Wallachia
  "CNN", #Connacht
  "CRN", #Cornwall
  "ENG", #England
  "GBR", #Great
  "IRE", #Ireland
  "LAN", #Lancaster
  "LEI", #Leinster
  "MNS", #Munster
  "NOL", #Northumberland
  "SCO", #Scotland
  "TYR", #Tyrone
  "WLS", #Wales
  "YOR", #York
  "BRZ", #Brazil
  "CAM", #United
  "CAN", #Canada
  "CHL", #Chile
  "COL", #Colombia
  "HAT", #Haiti
  "LAP", #La
  "LOU", #Louisiana
  "MEX", #Mexico
  "PEU", #Peru
  "QUE", #Quebec
  "USA", #USA
  "VNZ", #Venezuela
  "DNZ", #Danzig
  "KRA", #Krakow
  "KUR", #Kurland
  "LIT", #Lithuania
  "LIV", #Livonian
  "MAZ", #Mazovia
  "PLT", #Polotsk
  "POL", #Poland
  "PRU", #Prussia
  "RIG", #Riga
  "TEU", #Teutonic
  "ALS", #Alsace
  "AMG", #Armagnac
  "AUV", #Auvergne
  "AVI", #Avignon
  "BAR", #Bar
  "BER", #Berry
  "BOU", #Bourbonnais
  "BRI", #Brittany
  "BUR", #Burgundy
  "CHP", #Champagne
  "COR", #Corsica
  "DAU", #Dauphine
  "FOI", #Foix
  "FRA", #France
  "GUY", #Guyenne
  "LOR", #Lorraine
  "NEV", #Nevers
  "NRM", #Normandy
  "ORL", #Orleans
  "PRO", #Provence
  "RFR", #Revolutionary
  "TOU", #Toulouse
  "ANH", #Anhalt
  "ANS", #Ansbach
  "HAB", #Austria
  "BAD", #Baden
  "BAV", #Bavaria
  "BOH", #Bohemia
  "BRA", #Brandenburg
  "BRE", #Bremen
  "BRU", #Brunswick
  "FRN", #Frankfurt
  "KLE", #Cleves
  "KOL", #Cologne
  "GER", #Germany
  "HAM", #Hamburg
  "HAN", #Hannover
  "HSA", #The
  "HES", #Hesse
  "LAU", #Saxe-Lauenburg
  "LUN", #Luneburg
  "MAG", #Magdeburg
  "MAI", #Mainz
  "MKL", #Mecklenburg
  "MUN", #Munster
  "OLD", #Oldenburg
  "PAL", #Palatinate
  "POM", #Pommerania
  "SAX", #Saxony
  "SIL", #Silesia
  "SLZ", #Salzburg
  "STY", #Styria
  "SWI", #Switzerland
  "THU", #Thuringia
  "TIR", #Tirol
  "TRI", #Trier
  "ULM", #Ulm
  "WBG", #Wurzburg
  "WES", #Westphalia
  "WUR", #Wurttemberg
  "ARA", #Aragon
  "CAS", #Castille
  "CAT", #Catalunya
  "GRA", #Granada
  "NAV", #Navarra
  "POR", #Portugal
  "SPA", #Spain
  "AQU", #Aquileia
  "ETR", #Etruria
  "FER", #Ferrara
  "GEN", #Genoa
  "ITA", #Italy
  "MAN", #Mantua
  "MLO", #Milan
  "MOD", #Modena
  "NAP", #Naples
  "PAP", #Papal
  "PAR", #Parma
  "PIS", #Pisa
  "SAR", #Sardinia
  "SPI", #Sardinia-Piedmont
  "SAV", #Savoy
  "SIC", #Sicily
  "SIE", #Siena
  "TUS", #Tuscany
  "URB", #Urbino
  "VEN", #Venice
  "BRB", #Brabant
  "FLA", #Flanders
  "FRI", #Friesland
  "GEL", #Gelre
  "HAI", #Hainaut
  "HOL", #Holland
  "LIE", #Liege
  "LUX", #Luxembourg
  "NED", #Netherlands
  "UTR", #Utrecht
  "ARM", #Armenia
  "AST", #Astrakhan
  "CRI", #Crimea
  "GEO", #Georgia
  "GOL", #Golden
  "KAZ", #Kazan
  "MOS", #Muscovy
  "MUR", #Murom
  "NOV", #Novgorod
  "NZH", #Nizhny
  "NOG", #Nogai
  "PSK", #Pskov
  "QAS", #Qasim
  "RUS", #Russia
  "RYA", #Ryazan
  "SIB", #Sibir
  "SMO", #Smolensk
  "TVE", #Tver
  "UKR", #Ukraine
  "YAR", #Yaroslavl
  "ZAZ", #Zaporozhie
  "ALH", #Haasa
  "HED", #Hedjaz
  "NAJ", #Najd
  "OMA", #Oman
  "SHR", #Sharjah
  "ADE", #Yemen
  "AKK", #Ak
  "AYD", #Aydin
  "CND", #Candar
  "DUL", #Dulkadir
  "KAR", #Karaman
  "MEN", #Mentese
  "RAM", #Ramazan
  "SRU", #Saruhan
  "TRE", #Trebizond
  "ALG", #Algiers
  "FEZ", #Fez
  "MAM", #Mamluks
  "MOR", #Morocco
  "TRP", #Tripoli
  "TUN", #Tunisia
  "KZH", #Kazakh
  "KHI", #Khiva
  "KOK", #Kokkand
  "SHY", #Shaybanid
  "DUR", #Durrani
  "PER", #Persia
  "QAR", #Qara
  "SYR", #Syria
  "TIM", #Timurid
  "JAI", #Jalayrids
  "AZT", #Aztecs
  "CHE", #Cherokee
  "CHM", #Chimu
  "CRE", #Creek
  "HUR", #Huron
  "INC", #Inca
  "IRO", #Iroquois
  "MAY", #Maya
  "SHA", #Shawnee
  "ZAP", #Zapotec
  "ADA", #Adal
  "ASH", #Ashanti
  "BEN", #Benin
  "ETH", #Ethiopia
  "NUB", #Funj
  "HAU", #Hausa
  "KBO", #Kanem
  "KON", #Kongo
  "LOA", #Loango
  "MAL", #Mali
  "ZIM", #Mutapa
  "SON", #Songhai
  "ZAN", #Swahili
  "OYO", #Oyo
  "SOF", #Segu
  "ANN", #Annam
  "ARK", #Arakan
  "ATJ", #Atjeh
  "AYU", #Ayutthaya
  "BLI", #Bali
  "BAN", #Banten
  "BEI", #Brunei
  "CHA", #Champa
  "CHG", #Chagatai
  "CHK", #Champassak
  "DAI", #Dai
  "FUJ", #Fujiwara
  "JAP", #Japan
  "KHA", #Mongol
  "KHM", #Khmer
  "KOR", #Korea
  "LNA", #LanNa
  "LUA", #Luang
  "LXA", #Lan
  "MCH", #Manchu
  "MIN", #Minamoto
  "MKS", #Makassar
  "MLC", #Malacca
  "MNG", #Ming
  "MTR", #Mataram
  "OIR", #Oirat
  "PAT", #Pattani
  "PEG", #Pegu
  "RYU", #Ryukyu
  "SST", #Shan
  "SUL", #Sulu
  "TAC", #Tachibana
  "TAI", #Taira
  "TAU", #Taungu
  "TIB", #Tibet
  "TOK", #Tonkin
  "VIE", #Vientiane
  "WUU", #Wu
  "XIA", #Xia
  "ASS", #Assam
  "BAS", #Ahmadnagar
  "BAL", #Baluchistan
  "BNG", #Bengal
  "BRR", #Berar
  "BHO", #Bhonsle
  "BHU", #Bhutan
  "AHM", #Bihar
  "BIJ", #Bijapur
  "BND", #Bundelkhand
  "BAH", #Deccan
  "DLH", #Delhi
  "GAK", #Gakwar
  "GOC", #Golcanda
  "GDW", #Gondwana
  "GUJ", #Gujarat
  "HIN", #Hindustan
  "HYD", #Hyderabad
  "KRK", #Carnatic
  "KSH", #Kashmir
  "KHD", #Khandesh
  "KTH", #Ceylon
  "MAD", #Madurai
  "MAR", #Maharasthra
  "MLB", #Manipur
  "MLD", #Maldive
  "MLW", #Malwa
  "MUG", #Mughal
  "MYS", #Mysore
  "NIZ", #Deva
  "NPL", #Nepal
  "ORI", #Orissa
  "ODH", #Oudh
  "PUN", #Punjab
  "RAJ", #Rajputna
  "SND", #Sind
  "TRV", #Travanacore
  "VIJ" #Vijayanagar
]
